### ISSUE TITLE
License expired again

### ISSUE THREAD

**Issue by kehao95** [tsroten/pynlpir#67]
Sadly found out that the license file failed again. And the [NLPIR project](https://github.com/NLPIR-team/NLPIR ) has been changed a lot.  
There is no single license anymore. And it divided the functions into components. Still undocumented.
This project is no longer working before major changes.

Thank you for your work on this project you've helped me a lot.

Personally, I don't recommend you spend much of your time on such a closed source project. Especially when their documents are so out of date, and the licenses expire weekly/monthly.

**Comment by tsroten** [comment]
@kehao95 Yes, NLPIR licenses are hard to understand. I'm not quite sure what they accomplish since the licenses are available on GitHub for download. 

You should be able to [use this license](https://github.com/NLPIR-team/NLPIR/blob/master/License/license%20for%20a%20month/NLPIR-ICTCLAS%E5%88%86%E8%AF%8D%E7%B3%BB%E7%BB%9F%E6%8E%88%E6%9D%83/NLPIR.user).

**Comment by tsroten** [comment]
@kehao95 If you update via `pip install --upgrade pynlpir` to the newest version, you can auto-update the license by running `pynlpir update`.

**Comment by kehao95** [comment]
thank you~ 😃
